# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/cmadc/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

pod 'KKRouter'
pod 'UITableView+FDTemplateLayoutCell'

target 'Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Example

end
